[package]
name = "sensehat"
version = "0.1.0"
authors = ["Jonathan Pallant <github@thejpster.org.uk>"]
license-file = "LICENSE.md"

[dependencies]
# measurements = "0.2.1"
measurements = { git = "https://github.com/thejpster/rust-measurements" }
i2cdev = "0.3.1"
byteorder = "1.0.0"
