[package]
name = "sensehat"
version = "0.1.1"
authors = ["Jonathan Pallant <github@thejpster.org.uk>"]
license-file = "LICENSE.md"
documentation = "https://docs.rs/crate/sensehat"
repository = "https://github.com/thejpster/sensehat-rs"
keywords = ["sensehat", "raspberry", "pi", "sensors"]
description = "Interface with the Raspberry Pi Foundation's official Sense Hat sensor board."
readme = "README.md"

[dependencies]
measurements = "0.4.0"
i2cdev = "0.3.1"
byteorder = "1.0.0"
